name: "Stable branch continuous build"
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: ~
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        php-versions: ['8.0']
        composer-versions: ['composer:v2']
      fail-fast: false
    name: Building on ${{ matrix.php-versions }} @ ${{ matrix.os }} with ${{ matrix.composer-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 0
      - name: Install & Configure PHP
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: ${{ matrix.php-versions }}
          tools: ${{ matrix.composer-versions }}
          extensions: xdebug, mbstring, posix, gmp, bcmath
      - name: Check Versions
        run: |
          php -v
          php -m
          composer --version
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Run Tests
        run: php bin/grumphp run --no-interaction
        env:
          XDEBUG_MODE: coverage
      - name: fix code coverage paths
        if: contains(matrix.os, 'ubuntu-latest') && ${{ !env.ACT }}
        working-directory: .
        run: |
          sed -i 's/\/home\/runner\/work\/types\/types\//\/github\/workspace\//g' build/phpunit/logs/clover.xml
          sed -i 's/\/home\/runner\/work\/types\/types\//\/github\/workspace\//g' build/phpunit/logs/junit.xml
      - name: Starting SonarCloud Scan
        if: contains(matrix.os, 'ubuntu-latest') && ${{ !env.ACT }}
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Generate Failure Badge on Failure
        if: ${{ failure() }}
        uses: Schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 027dcddb6a1dc1995a2a47e528aaf020
          filename: build-stable.json
          label: Build
          message: failing
          color: red
  make_badge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Generate succesful badge
        uses: Schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 027dcddb6a1dc1995a2a47e528aaf020
          filename: build-stable.json
          label: Build
          message: passing
          color: green
