name: "Continuous patching"
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch: ~

jobs:
  test_and_patch:
    runs-on: ubuntu-latest
    name: Auto-upgrades composer lock file and tests against latest versions.
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Install & Configure PHP
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: '8.0'
          tools: 'composer:v2'
          extensions: mbstring, posix, gmp, bcmath
      - name: Check Versions
        run: |
          php -v
          php -m
          composer --version
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Update dependencies
        run: composer update --no-progress --prefer-dist
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Run Tests with no coverage
        if: steps.changes.outputs.changed == 1
        run: php bin/grumphp run --no-interaction
      - name: Commit changes if everything is ok.
        if: ${{ success() }} && steps.changes.outputs.changed == 1
        uses: EndBug/add-and-commit@v7
        with:
          author_name: PHPTyping
          author_email: phptyping@noreply.com
          message: Updating dependencies in ${{ github.run_id }}
          add: '.'
          push: true
          branch: master
  make_badge:
    runs-on: ubuntu-latest
    needs: test_and_patch
    if: contains(github.ref, "master")
    steps:
      - name: Generate Patch Badge
        uses: Schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: d18a6a553c2308b59df916c29ce64eb6
          filename: patching.json
          label: Patching
          message: passing
          color: green
