name: "Mark stale issues and pull requests"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: ~

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v3
        with:
          days-before-stale: 30
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Issue marked as stale after 30 days of inactivity.'
          stale-pr-message: 'PR marked as stale after 30 days of inactivity.'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
