name: "Runs tests & checks"
on:
  pull_request:
    branches: [ master, develop ]
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        php-versions: ['8.0']
        composer-versions: ['composer:v2']
      fail-fast: false
    name: Building on ${{ matrix.php-versions }} @ ${{ matrix.os }} with ${{ matrix.composer-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Install & Configure PHP
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: ${{ matrix.php-versions }}
          tools: ${{ matrix.composer-versions }}
          extensions: xdebug, mbstring, posix, gmp, bcmath
      - name: Check Versions
        run: |
          php -v
          php -m
          composer --version
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Run Tests
        run: php bin/grumphp run --no-interaction
        env:
          XDEBUG_MODE: coverage
      - name: fix code coverage paths
        if: contains(matrix.os, 'ubuntu-latest')
        working-directory: .
        run: |
          sed -i 's/\/home\/runner\/work\/types\/types\//\/github\/workspace\//g' build/phpunit/logs/clover.xml
          sed -i 's/\/home\/runner\/work\/types\/types\//\/github\/workspace\//g' build/phpunit/logs/junit.xml
      - name: Starting SonarCloud Scan
        if: contains(matrix.os, 'ubuntu-latest')
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
